spring:
  datasource:
    url: jdbc:postgresql://localhost/contacts
    username: contactUser  
    password: contactUser
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
       
       
       
jwt:
  expirationTime: 3600000
  secret: mySuperSecret 