spring:
  datasource:
    url: jdbc:postgresql://localhost/contacts
    username: contactUser  
    password: contactUser
    
    
  liquibase:
    change-log: classpath:liquibase/liquibase.xml
    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
       
       
       
jwt:
  expirationTime: 10800000
  secret: mySuperSecret 